# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0002_auto_20180419_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/media/default_barber.jpg', upload_to='barber_photo')),
                ('first_last_name', models.CharField(max_length=128)),
                ('descritpion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompletedCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='barbers',
            name='completed_courses',
            field=models.ManyToManyField(to='hairdresser.CompletedCourses'),
        ),
    ]
