# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0003_auto_20180419_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbers',
            old_name='descritpion',
            new_name='description',
        ),
    ]
