# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0004_auto_20180419_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbers',
            name='image',
            field=models.ImageField(default='default_barber.jpg', upload_to='barber_photo'),
        ),
    ]
