# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0005_auto_20180420_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='salon_photo')),
                ('header', models.CharField(max_length=256)),
                ('content', models.TextField()),
            ],
        ),
    ]
