# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0006_saloninfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
