# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0007_pricetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='products_photos')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('quantity', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
