# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_table_widget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetablewidgetpluginmodel',
            name='limit_per_page',
            field=models.IntegerField(default=10, verbose_name='Ilość usług'),
        ),
    ]
