# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsListWidgetPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='news_list_widget_newslistwidgetpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('limit_per_page', models.IntegerField(default=10, verbose_name='Ilość newsów na stronie')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
